spring:
  application:
    name: customer-support-ticket-system
  datasource:
    url: jdbc:h2:mem:ticketdb
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true   # to initialize h2 db before the execution of data.sql
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always



#  security:
#    user:
#      name: "Poonam"
#      password": "pwd1"

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: DEBUG
        security: DEBUG


