spring:
  application:
    name: customer-support-ticket-system
  datasource:
    url: jdbc:h2:mem:ticketdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


